spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://211.37.174.19:3306/jws_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: jws_id
    password: jws_pw

#mybatis:
#    type-aliases-package: com.websit.trip.dto
#    mapper-locations: classpath:mybatis/mapper/**/*.xml